import { useState } from "react";
import { Sparkles, Mic, Square, FileCheck2 } from "lucide-react";
import { toast } from "sonner";
import { useStore } from "../store";
import { Page, Card, Button, Badge, AIBox, Select } from "../components";
import { can } from "../permissions";

export function AIInsights() {
  const s = useStore();
  const [ambient, setAmbient] = useState<
    "idle" | "recording" | "processing" | "draft" | "approved"
  >("idle");
  const [ambientPatient, setAmbientPatient] = useState(s.patients[0]?.id || "");
  const clinicalApprover = can(s.role, "clinical-review");
  const delayed = s.admissions.filter(
    (a) =>
      a.status === "Active" && a.blockers.some((b) => b.status === "Blocked"),
  );
  const noShows = s.appointments.filter((a) => a.status === "No-show").length;
  const patterns = Object.entries(
    s.incidents.reduce<Record<string, number>>(
      (a, i) => ({
        ...a,
        [`${i.medication} · ${i.ward}`]:
          (a[`${i.medication} · ${i.ward}`] || 0) + 1,
      }),
      {},
    ),
  ).filter(([, n]) => n > 1);
  const generate = () => {
    setAmbient("processing");
    setTimeout(() => setAmbient("draft"), 700);
  };
  return (
    <Page
      title="AI Insights"
      subtitle="Human-reviewed operational intelligence generated from synthetic CareOps activity."
    >
      <div className="grid thirds">
        <AIBox>
          <h3>{delayed.length} delayed-discharge risks</h3>
          <p>
            Pharmacy, transport and diagnostics dependencies need coordinator
            attention.
          </p>
        </AIBox>
        <AIBox>
          <h3>{noShows} recorded no-shows</h3>
          <p>Use preference-aware reminders before upcoming clinics.</p>
        </AIBox>
        <AIBox>
          <h3>{patterns.length} recurring safety patterns</h3>
          <p>Pattern signals require safety officer validation.</p>
        </AIBox>
      </div>
      <div className="grid two">
        <Card>
          <div className="cardhead">
            <div>
              <h2>Ambient Documentation Demo</h2>
              <p>Fictional consultation · no audio is captured</p>
            </div>
            <Badge tone="ai">DEMO AI</Badge>
          </div>
          <label className="ambientpatient">
            Consultation patient
            <Select
              value={ambientPatient}
              onChange={(event) => setAmbientPatient(event.target.value)}
            >
              {s.patients.map((patient) => (
                <option key={patient.id} value={patient.id}>
                  {patient.firstName} {patient.lastName}
                </option>
              ))}
            </Select>
          </label>
          {ambient === "idle" && (
            <div className="ambientempty">
              <Mic />
              <h3>Start demo consultation</h3>
              <p>A scripted synthetic transcript will appear.</p>
              <Button onClick={() => setAmbient("recording")}>
                <Mic />
                Start Demo Consultation
              </Button>
            </div>
          )}
          {ambient === "recording" && (
            <>
              <div className="transcript">
                <p>
                  <b>Clinician:</b> How have you felt since your last review?
                </p>
                <p>
                  <b>Patient:</b> The discomfort has reduced, but I still become
                  tired after walking.
                </p>
                <p>
                  <b>Clinician:</b> We will review the results and arrange
                  follow-up.
                </p>
              </div>
              <Button onClick={generate}>
                <Square />
                End & Generate Clinical Note
              </Button>
            </>
          )}
          {ambient === "processing" && (
            <div className="processing">
              <div className="spinner" />
              <h3>Structuring documentation draft…</h3>
            </div>
          )}
          {(ambient === "draft" || ambient === "approved") && (
            <div className="clinicaldraft">
              <div className="aititle">
                <Sparkles />
                AI-generated documentation draft
              </div>
              <h4>Chief Complaint</h4>
              <textarea defaultValue="Exertional fatigue with improving chest discomfort." />
              <h4>History</h4>
              <textarea defaultValue="Patient reports improvement since the previous review but persistent fatigue on walking." />
              <h4>Assessment Notes</h4>
              <textarea defaultValue="Symptoms require correlation with reviewed investigation results. No diagnosis generated by the demo." />
              <h4>Actions & Follow-up</h4>
              <textarea defaultValue="Review results and arrange appropriate clinical follow-up." />
              <small>Requires clinician review before use.</small>
              {ambient === "draft" && (
                <div className="modalactions">
                  <Button variant="danger" onClick={() => setAmbient("idle")}>
                    Discard
                  </Button>
                  {clinicalApprover ? (
                    <Button
                      onClick={() => {
                        s.addNote(
                          ambientPatient,
                          "Ambient documentation draft approved: Exertional fatigue with improving chest discomfort. History reviewed; investigation results and follow-up remain subject to clinician review.",
                        );
                        setAmbient("approved");
                        toast.success(
                          "Draft approved and added to selected patient record",
                        );
                      }}
                    >
                      <FileCheck2 />
                      Approve Draft
                    </Button>
                  ) : (
                    <Badge tone="warning">Clinician approval required</Badge>
                  )}
                </div>
              )}
              {ambient === "approved" && (
                <Badge tone="success">Approved by clinician</Badge>
              )}
            </div>
          )}
        </Card>
        <Card>
          <h2>Prioritized recommendations</h2>
          {delayed.map((a) => (
            <div className="insightrow" key={a.id}>
              <Sparkles />
              <div>
                <b>Review discharge dependencies for {a.patientId}</b>
                <p>
                  {a.blockers
                    .filter(
                      (b) =>
                        b.status !== "Complete" && b.status !== "Not Required",
                    )
                    .map((b) => b.name)
                    .join(", ")}
                </p>
                <small>Generated just now · Human review required</small>
              </div>
            </div>
          ))}
          {patterns.map(([p, n]) => (
            <div className="insightrow" key={p}>
              <Sparkles />
              <div>
                <b>Review recurring {p} incidents</b>
                <p>{n} similar approved/reported events detected.</p>
                <small>Safety signal, not a clinical conclusion</small>
              </div>
            </div>
          ))}
        </Card>
      </div>
    </Page>
  );
}
