export { Overview } from "./Overview";
export { Patients, PatientDetail } from "./Patients";
export { Referrals } from "./Referrals";
export { WaitingList } from "./WaitingList";
export { Appointments } from "./Appointments";
export { PatientFlow } from "./PatientFlow";
export { MedicationSafety } from "./MedicationSafety";
export { SafetyAnalytics } from "./SafetyAnalytics";
export { Copilot } from "./Copilot";
export { Population, Portal, Integrations, SettingsPage } from "./More";
export { AIInsights } from "./AIInsights";
