import type {
  Patient,
  Referral,
  WaitEntry,
  Appointment,
  Bed,
  Admission,
  Incident,
} from "./types";
const tl = (id: string, type: string, summary: string) => ({
  id,
  at: "2026-08-11T09:30:00",
  type,
  summary,
  source: "CareOps Demo",
});
export const patients: Patient[] = [
  {
    id: "P-10024",
    firstName: "James",
    lastName: "Sutton",
    dob: "1968-03-04",
    sex: "Male",
    phone: "07123 555 184",
    email: "j.sutton@example.demo",
    language: "English",
    ward: "Ward 4B",
    status: "Admitted",
    consent: { sms: true, email: true, portal: true },
    timeline: [
      tl("t1", "Admission", "Admitted to Ward 4B"),
      tl("t2", "Referral", "Cardiology referral approved"),
    ],
  },
  {
    id: "P-10031",
    firstName: "Amina",
    lastName: "Rahman",
    dob: "1977-11-19",
    sex: "Female",
    phone: "07222 310 882",
    email: "amina.rahman@example.demo",
    language: "English",
    ward: "Outpatient",
    status: "Waiting",
    consent: { sms: true, email: false, portal: true },
    timeline: [tl("t3", "Referral", "Neurology referral received")],
  },
  {
    id: "P-10045",
    firstName: "Elena",
    lastName: "Marin",
    dob: "1985-06-22",
    sex: "Female",
    phone: "07333 947 210",
    email: "elena.marin@example.demo",
    language: "Spanish",
    ward: "Outpatient",
    status: "Active",
    consent: { sms: true, email: true, portal: true },
    timeline: [tl("t4", "Registration", "Patient registered")],
  },
  {
    id: "P-10052",
    firstName: "Oliver",
    lastName: "Bennett",
    dob: "1959-01-13",
    sex: "Male",
    phone: "07444 228 901",
    email: "o.bennett@example.demo",
    language: "English",
    ward: "Ward 4B",
    status: "Admitted",
    consent: { sms: false, email: true, portal: false },
    timeline: [tl("t5", "Admission", "Admitted for respiratory observation")],
  },
];
export const referrals: Referral[] = [
  {
    id: "R-2408",
    patientId: "P-10031",
    source: "Riverside Family Practice",
    service: "Neurology",
    suggested: "Neurology",
    urgency: "Urgent",
    status: "Needs Review",
    received: "2026-08-11",
    missing: ["Recent blood panel"],
    confidence: 92,
  },
  {
    id: "R-2399",
    patientId: "P-10045",
    source: "Northgate Clinic",
    service: "Cardiology",
    suggested: "Cardiology",
    urgency: "Routine",
    status: "Approved",
    received: "2026-08-08",
    missing: [],
    confidence: 96,
  },
];
export const waiting: WaitEntry[] = [
  {
    id: "W-501",
    patientId: "P-10045",
    referralId: "R-2399",
    specialty: "Cardiology",
    priority: "Routine",
    since: "2026-08-08",
    missing: [],
    targetDays: 28,
    noShows: 0,
    risk: "Low",
    status: "Waiting",
  },
];
export const appointments: Appointment[] = [
  {
    id: "A-801",
    patientId: "P-10045",
    practitioner: "Dr Sarah Wilson",
    specialty: "Cardiology",
    date: "2026-08-13",
    time: "09:00",
    location: "Clinic 2",
    type: "Consultation",
    status: "Confirmed",
    reminder: "11 Aug, 09:15",
  },
];
export const beds: Bed[] = [
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `4B-${i + 1}`,
    ward: "Ward 4B",
    status: (i < 2 ? "Occupied" : "Available") as Bed["status"],
    patientId: i === 0 ? "P-10024" : i === 1 ? "P-10052" : undefined,
  })),
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `ICU-${i + 1}`,
    ward: "ICU",
    status: "Available" as const,
  })),
];
export const admissions: Admission[] = [
  {
    id: "AD-91",
    patientId: "P-10024",
    ward: "Ward 4B",
    bedId: "4B-1",
    consultant: "Dr Maya Chen",
    reason: "Chest pain investigation",
    expected: "2026-08-12",
    status: "Active",
    blockers: [
      { id: "b1", name: "Clinical Review", status: "Complete" },
      { id: "b2", name: "Diagnostics", status: "Complete" },
      { id: "b3", name: "Pharmacy", status: "Blocked" },
      { id: "b4", name: "Transport", status: "Pending" },
    ],
  },
  {
    id: "AD-92",
    patientId: "P-10052",
    ward: "Ward 4B",
    bedId: "4B-2",
    consultant: "Dr Ishan Patel",
    reason: "Respiratory observation",
    expected: "2026-08-14",
    status: "Active",
    blockers: [
      { id: "b5", name: "Clinical Review", status: "Pending" },
      { id: "b6", name: "Diagnostics", status: "Blocked" },
    ],
  },
];
export const incidents: Incident[] = [
  {
    id: "MI-302",
    patientId: "P-10052",
    medication: "Metoprolol",
    prescribed: "25mg",
    administered: "50mg",
    type: "Wrong Dose",
    severity: "Moderate",
    ward: "Ward 4B",
    narrative:
      "Higher dose administered during evening round. No immediate harm observed.",
    status: "Approved",
    at: "2026-08-06T20:00:00",
  },
  {
    id: "MI-298",
    patientId: "P-10024",
    medication: "Metoprolol",
    prescribed: "25mg",
    administered: "50mg",
    type: "Wrong Dose",
    severity: "Moderate",
    ward: "Ward 4B",
    narrative: "Dose discrepancy identified after administration.",
    status: "Closed",
    at: "2026-07-28T20:15:00",
  },
];
